#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    centerLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  frontTouch,     sensorTouch)
#pragma config(Sensor, dgtl7,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl11, armEncoder,     sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  rightIME,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftIME,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  armIME,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, driveRight, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int movePower = 25;
int shutoff;
int sonarshutoff;
int checkLines()
{
	if(SensorValue[centerLineFollower] > 2000 \
		&& SensorValue[rightLineFollower] > 2000 \
	&& SensorValue[leftLineFollower] > 2000)
	{
		return 1;
	}
	return 0;
}
task main()
{
	while(true)
	{

		/* Step 1 */
		/* Checks if the button on the front is pressed. If it is, it runs the code below it */
		if(SensorValue[frontTouch] == 1)
		{
			/* Step 2 */
			/* Waits until the button is unpressed */
			waitUntil(SensorValue[frontTouch] == 0);

			/* Step 3 */
			/* Repeats the code below until the button is pressed */
			while(SensorValue[frontTouch] == 0)
			{
				/* Step 4 */
				/* Checks whether the surface under the line follower is black and whether the variable "shutoff" is
				activated. if it is then it will loop the code underneath until one of the two conditions stops being
				true */
				if(checkLines())
				{
					if(SensorValue[frontTouch] == 1)
					{
						/* Step 6 */
						/* Changes the variable "shutoff" to one. Since this is a requirement of the loop the loop stops */
						shutoff = 1;
					}
					/* Jolt right, then continuously turn right until centerLineFollower > 2000 */
					turnRight(250, milliseconds, movePower);
					while(SensorValue[rightLineFollower] < 2000)
					{
						if(SensorValue[frontTouch] == 1)
						{
							shutoff = 1;
						}
						turnRight(20, milliseconds, movePower);
					}


					{
						/* Step 6 */
						/* Changes the variable "shutoff" to one. Since this is a requirement of the loop the loop stops */
						shutoff = 1;
					}
					{
						turnRight(30, milliseconds, movePower);
					}
				}
				while(SensorValue[centerLineFollower] > 2000 && shutoff == 0 && checkLines() == 0 && sonarshutoff == 0)
				{
					/* Step 5 */
					/* Checks to see whether the button is pressed. If so it runs the code below */
					if(SensorValue[frontTouch] == 1)
					{
						/* Step 6 */
						/* Changes the variable "shutoff" to one. Since this is a requirement of the loop the loop stops */
						shutoff = 1;
					}

					if (SensorValue[sonarSensor] > 20) {
						sonarshutoff = 1;
					}
					/* Step 7 */
					/* Moves the robot forward for 100 milliseconds at half power */
					forward(30, milliseconds, movePower);

					/* Step 4 */
					while(SensorValue[leftLineFollower] > 2000 && shutoff == 0 && checkLines() == 0)
					{
						/* Step 5 */
						if(SensorValue[frontTouch] == 1)
						{
							/* Step 6 */
							shutoff = 1;
						}
						/* Step 7 */
						turnLeft(10, milliseconds, movePower);
					}
					/* Step 4 */
					while(SensorValue[rightLineFollower] > 2000 && shutoff == 0 && checkLines() == 0)
					{
						/* Step 5 */
						if(SensorValue[frontTouch] == 1)
						{
							/* Step 6 */
							shutoff = 1;
						}
						/* Step 7 */
						turnRight(10, milliseconds, movePower);
					}


				}
				/* Step 8 */
				/* Waits until the button stops being pressed */
				waitUntil(SensorValue[frontTouch] == 0);
				/* Step 9 */
				/* Resets the "shutoff" variable */
				shutoff = 0;


			}
		}
	}
}
