#pragma config(StandardModel, "RVW CLAWBOT")
#pragma config(RenamedStdModelSensor, dgtl6, frontTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int shutoff;
task main()
{
	while(true)
	{
		/* Step 1 */
		/* Checks if the button on the front is pressed. If it is, it runs the code below it */
		if(SensorValue[frontTouch] == 1)
		{
			/* Step 2 */
			/* Waits until the button is unpressed */
			waitUntil(SensorValue[frontTouch] == 0);

			/* Step 3 */
			/* Repeats the code below until the button is pressed */
			while(SensorValue[frontTouch] == 0)
			{
				/* Step 4 */
				/* Checks whether the surface under the line follower is black and whether the variable "shutoff" is
				activated. if it is then it will loop the code underneath until one of the two conditions stops being
				true */
				while(SensorValue[centerLineFollower] > 2000 && shutoff == 0)
				{
					/* Step 5 */
					/* Checks to see whether the button is pressed. If so it runs the code below */
					if(SensorValue[frontTouch] == 1)
					{
						/* Step 6 */
						/* Changes the variable "shutoff" to one. Since this is a requirement of the loop the loop stops */
						shutoff = 1;
						}
						/* Step 7 */
						/* Moves the robot forward for 100 milliseconds at half power */
						forward(30, milliseconds, 50);
						}
				/* Step 4 */
				while(SensorValue[leftLineFollower] > 2000 && shutoff == 0)
				{
					/* Step 5 */
					if(SensorValue[frontTouch] == 1)
					{
						/* Step 6 */
						shutoff = 1;
					}
					/* Step 7 */
					turnLeft(10, milliseconds, 50);
				}
				/* Step 4 */
				while(SensorValue[rightLineFollower] > 2000 && shutoff == 0)
				{
					/* Step 5 */
					if(SensorValue[frontTouch] == 1)
					{
						/* Step 6 */
						shutoff = 1;
					}
					/* Step 7 */
					turnRight(10, milliseconds, 50);
				}
			}
			/* Step 8 */
			/* Waits until the button stops being pressed */
			waitUntil(SensorValue[frontTouch] == 0);
			/* Step 9 */
			/* Resets the "shutoff" variable */
			shutoff = 0;


		}
	}
}
